### ISSUE TITLE
hyperref Package with Certain Options Raises an Error

### ISSUE THREAD

**Issue by ravehe** [psibre/2017-essv-authorkit#2]
## Description

When the package _hyperref_ is used with the options [hidelinks,pdfusetitle], an error is raised while compiling: "Option clash for package hyperref."
**Note**: if the packages is used without options, the error does not occur. 

Reproducible? - yes (see minimal example)

## Minimal Example
If the line \usepackage[hidelinks,pdfusetitle]{hyperref} if commented out, compiling is successful. 
```
\documentclass[12pt, a4paper]{article}

\usepackage{essv}
\usepackage[hidelinks,pdfusetitle]{hyperref}

\title{Hyperref Bug Minimal Example}
\author{No Aouthor$^1$}
\affil{$^1$Universität des Saarlandes,}
\email{minimalexample@coli.uni-saarland.de}

\begin{document}
	\maketitle
	\section{Example}
	This is a minimal example
\end{document}
```

**Comment by psibre** [comment]
Thanks for details!

`essv.sty` defines
```latex
% hyperlinks
\RequirePackage[%
  colorlinks,
  linkcolor=black,
  citecolor=black,
  urlcolor=black,
  pdfusetitle
]{hyperref}
```
`hidelinks` would be more elegant, but is not available on older TeXLive installations. Coloring all links black has the same effect (within reason), but clashes with `hidelinks` if the latter is also specified...

As a workaround, if an author really wants to *hide* links instead of coloring them black, it is possible to specify in the main document,
```latex
\PassOptionsToPackage{hidelinks}{hyperref}
```
